### ISSUE TITLE
NullPointerException at replacement

### ISSUE THREAD

**Issue by ksclarke** [1tchy/variable-search-replace-plugin#1]
Hi, I get a NullPointerException from https://github.com/1tchy/variable-search-replace-plugin/blob/master/src/main/java/io/github/itchy/maven/plugins/variablesearchreplace/VariableSearchReplaceMojo.java#L35

I want to replace the found string with nothing. I see the "replacement" value isn't marked as required, but when I leave it out of the config I get a NPE (because it's not set with anything and has no default). If I just create an empty element (i.e. &lt;replacement&gt;&lt;/replacement&gt;) I also get a NPE. It doesn't seem like it's currently possible to replace with nothing (i.e. remove the text)?

Seems like if you made the default value for replacement an empty string this would work?

**Comment by 1tchy** [comment]
Hi, thanks for your report. I think I fixed it with 0a74f5d6f3f1f5ed68684ed17a7d69ec31782286.

I've also release a new version (1.1) from this plugin. Can you try again with this?

**Comment by ksclarke** [comment]
Yes, that fixes it. Thanks for the speedy response/update!
